### ISSUE TITLE
打开页面会有闪屏式的刷新

### ISSUE THREAD

**Issue by duansheli** [github-young/hugo-theme-next#2]
https://github-young.github.io/hugo-theme-next/

点击某个博文 
内容加载后，内容块部分闪屏式的刷新了一下 
点击回到首页， 也会出现闪屏式的刷新

**Comment by github-young** [comment]
> https://github-young.github.io/hugo-theme-next/
> 
> 点击某个博文
> 内容加载后，内容块部分闪屏式的刷新了一下
> 点击回到首页， 也会出现闪屏式的刷新

参见[这里](https://github.com/xtfly/hugo-theme-next/issues/15#issuecomment-565768450)

**Comment by duansheli** [comment]
@github-young 
代码块的对比度能调整吗 
https://github-young.github.io/hugo-theme-next/post/ThirdTest/
黑底 + 灰字  看起来比较吃力

比如这样
http://www.awslop.com/2019/11/16/jmh-dynamic-run.html

另外示例中的闪屏效果可以去掉啊 感觉这种应该算bug 不算特性吧

**Comment by github-young** [comment]
> @github-young
> 代码块的对比度能调整吗
> https://github-young.github.io/hugo-theme-next/post/ThirdTest/
> 黑底 + 灰字 看起来比较吃力
> 
> 比如这样
> http://www.awslop.com/2019/11/16/jmh-dynamic-run.html
> 
> 另外示例中的闪屏效果可以去掉啊 感觉这种应该算bug 不算特性吧

代码背景有个浅色的，我以前用过后来换成这个了，我下次维护的时候想想看设置一个选项。

刷新一次是hexo-next的特性，虽然我也不喜欢。你可以根据那个issue把相关的地方注释掉。下次commit我也会注释掉

**Comment by duansheli** [comment]
看到别人主题的效果 


* 树形列表块变色
https://www.nightfarmer.top/post/maven/#heading6

![image](https://user-images.githubusercontent.com/8579595/71418718-e82e5a80-26a6-11ea-826e-38af8f0dd1de.png)

**Comment by github-young** [comment]
> @github-young
> 代码块的对比度能调整吗
> https://github-young.github.io/hugo-theme-next/post/ThirdTest/
> 黑底 + 灰字 看起来比较吃力
> 
> 比如这样
> http://www.awslop.com/2019/11/16/jmh-dynamic-run.html
> 
> 另外示例中的闪屏效果可以去掉啊 感觉这种应该算bug 不算特性吧

代码块的配色方案可以自选，详见[这里](https://github.com/xtfly/hugo-theme-next/issues/17#issuecomment-569413459)

不过你上面图中的效果我觉得我做不出来，我也不是很熟悉html+css...
